/** Reviewed, intentionally abstract movement illustrations. They are visual
 * orientation only; written cues remain the source of instruction. */
export interface ExerciseVisual { id: string; label: string; reviewed: true; accent: string; }
export const EXERCISE_VISUALS: Record<string, ExerciseVisual> = {
  "ex-squat": { id: "ex-squat", label: "Standing squat illustration", reviewed: true, accent: "#8bd17c" },
  "ex-lunge": { id: "ex-lunge", label: "Forward lunge illustration", reviewed: true, accent: "#f2b66d" },
  "ex-deadlift": { id: "ex-deadlift", label: "Hip hinge illustration", reviewed: true, accent: "#8bd17c" },
  "ex-bench": { id: "ex-bench", label: "Press illustration", reviewed: true, accent: "#f2b66d" },
  "ex-ohp": { id: "ex-ohp", label: "Overhead press illustration", reviewed: true, accent: "#8bd17c" },
  "ex-row": { id: "ex-row", label: "Row illustration", reviewed: true, accent: "#f2b66d" },
  "ex-pullup": { id: "ex-pullup", label: "Pull-up illustration", reviewed: true, accent: "#8bd17c" },
  "ex-plank": { id: "ex-plank", label: "Plank illustration", reviewed: true, accent: "#f2b66d" },
  "ex-hlr": { id: "ex-hlr", label: "Hanging leg raise illustration", reviewed: true, accent: "#8bd17c" },
  "ex-run": { id: "ex-run", label: "Easy run illustration", reviewed: true, accent: "#f2b66d" },
  "ex-skipping": { id: "ex-skipping", label: "Skipping illustration", reviewed: true, accent: "#8bd17c" },
  "ex-yoga": { id: "ex-yoga", label: "Mobility illustration", reviewed: true, accent: "#f2b66d" },
  "ex-kettlebell": { id: "ex-kettlebell", label: "Kettlebell swing illustration", reviewed: true, accent: "#8bd17c" },
  "ex-walk": { id: "ex-walk", label: "Walking illustration", reviewed: true, accent: "#f2b66d" },
  "ex-chair-squat": { id: "ex-chair-squat", label: "Chair squat illustration", reviewed: true, accent: "#8bd17c" },
  "ex-glute-bridge": { id: "ex-glute-bridge", label: "Glute bridge illustration", reviewed: true, accent: "#f2b66d" },
  "ex-step-up": { id: "ex-step-up", label: "Step-up illustration", reviewed: true, accent: "#8bd17c" },
  "ex-wall-push": { id: "ex-wall-push", label: "Wall push illustration", reviewed: true, accent: "#f2b66d" },
  "ex-incline-push": { id: "ex-incline-push", label: "Incline push illustration", reviewed: true, accent: "#8bd17c" },
  "ex-band-row": { id: "ex-band-row", label: "Band row illustration", reviewed: true, accent: "#f2b66d" },
  "ex-bird-dog": { id: "ex-bird-dog", label: "Bird dog illustration", reviewed: true, accent: "#8bd17c" },
  "ex-dead-bug": { id: "ex-dead-bug", label: "Dead bug illustration", reviewed: true, accent: "#f2b66d" },
  "ex-side-plank": { id: "ex-side-plank", label: "Side plank illustration", reviewed: true, accent: "#8bd17c" },
  "ex-calf-raise": { id: "ex-calf-raise", label: "Calf raise illustration", reviewed: true, accent: "#f2b66d" },
  "ex-marching": { id: "ex-marching", label: "Standing march illustration", reviewed: true, accent: "#8bd17c" },
  "ex-step-touch": { id: "ex-step-touch", label: "Step touch illustration", reviewed: true, accent: "#f2b66d" },
  "ex-cat-cow": { id: "ex-cat-cow", label: "Cat cow illustration", reviewed: true, accent: "#8bd17c" },
  "ex-hip-flow": { id: "ex-hip-flow", label: "Hip mobility illustration", reviewed: true, accent: "#f2b66d" },
  "ex-sit-to-stand": { id: "ex-sit-to-stand", label: "Sit to stand illustration", reviewed: true, accent: "#8bd17c" },
  "ex-reverse-fly": { id: "ex-reverse-fly", label: "Band reverse fly illustration", reviewed: true, accent: "#f2b66d" },
};
